trajectory_planner:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
trajectory_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/high_level/input/nav_1"
safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/low_level/ackermann_cmd"
    published_drive_topic: "/vesc/low_level/input/safety"
